language: node_js
sudo: enabled
node_js:
  - "node"

before_script:
  - npm install gitbook-cli -g
  - sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py | sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read()); main()"
  - gitbook install .

script:
  - gitbook pdf .

deploy:
  provider: releases
  api_key: "b977f60643fe61c9ea20ae2fa5323232a0db0bd8"
  file: book.pdf
  skip_cleanup: true
  on:
    # tags设置为true表示只有在有tag的情况下才部署
    tags: true
