language: node_js
sudo: enabled
node_js:
- node
before_script:
- npm install gitbook-cli -g
- sudo -v && wget -nv -O- https://download.calibre-ebook.com/linux-installer.py |
  sudo python -c "import sys; main=lambda:sys.stderr.write('Download failed\n'); exec(sys.stdin.read());
  main()"
- gitbook install .
script:
- gitbook pdf .
deploy:
  provider: releases
  api_key:
    secure: 7cR30wcRD5snV1FnuPLwef1b7VzOWwkGdG1S2u90PAcuz5jnx2fL0p/WHDQ6aMsJoldtcrobpUjwOFw3lPWF45IfOrHikZzB2W9Jzm+WOtqRTwMXOGkK8+XL8Ez3mOYQxTw+lorMJKl/QQNaf6fEcmdzGvmVo0MlUIgPVPrKvUM9BNRH/901lUOjSdDmeSuTbThx1DQSSoIhe/2h0uNDc1LxA1A/Nqc2LMOK9L9dsMPDgc7K7n03g1ZHUi/hdEqtFzOkjG469TPTGcZf+EUx8mkq/QqU9CX84rr8174pVEfwCiGMgtulgULbiBk1+vBAOH+ord0GShS2Dkw4OvsZ0MW6IdhOmOi3Ya7FvrS6gHl+ALEtRenVU6N+BfW7KGqQhGD8UfqkXOBDrE0a0Oxqb7qRnTuekKnMpAoZ2qcgYl/a/IfYCujEIuMeod0+BPp9RFWjal3pqaQw0EUehGlD+2JFgcq+2lopRfpF7OMsJenWR4U12wQd6LomIpEzaBTxnpmKKgzd74W7DNZp2YobE1mJ5UwH2Duo/E3RR1yNlqnArNl92ggxB40bRKxXtPvf/B1pBPhRe1Jeh2TFn/bxVy3GPgVQNm+cO1TO2VI7j/lLsdXnr2D088nSeFFJvTLN6WTNjzX029r4HWMAIL8zqkZuRpS7UeglG/SU7RsdW44=
  file: book.pdf
  on:
    repo: Ir1d/A_Dance_With_OI
